### ISSUE TITLE
AttributeError: 'DataModel' object has no attribute 'NYrs'

### ISSUE THREAD

**Issue by drexeleds** [TheAcademyofNaturalSciences/gwlf-e#5]
When integrating GWLF-E in MMW in [this method](https://github.com/WikiWatershed/model-my-watershed/blob/3d4361f3273c1df507079bec33747a679e7f060d/src/mmw/apps/modeling/tasks.py#L426-L440), for the Lower Schuylkill HUC-10 we generate this input: [mapshed_data.json.txt](https://github.com/drexeleds/gwlf-e/files/2229049/mapshed_data.json.txt) (in JSON, actual input is a Python dictionary, so just `json.loads(mapshed_data.json.txt)` to get it), and for it get this error:

```[2018-07-25 09:36:09,417: ERROR/ForkPoolWorker-1] Task f105dd82-6791-4e21-b73d-1cba7d464e41 run from job 4145 raised exception: 'DataModel' object has no attribute 'NYrs'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 26, in wrapper
    return f(*args, **kw)
  File "/opt/app/apps/modeling/tasks.py", line 344, in run_gwlfe
    output = to_gms_file(model_input)
  File "/opt/app/apps/modeling/tasks.py", line 438, in to_gms_file
    writer.write(pre_z)
  File "/usr/local/lib/python2.7/dist-packages/gwlfe/Parser.py", line 1292, in write
    UnSatStorCarryover_f(z.NYrs, z.DaysMonth, z.Temp, z.InitSnow_0, z.Prec, z.NRur, z.NUrb, z.Area, z.CNI_0,
AttributeError: 'DataModel' object has no attribute 'NYrs' 
```

Can this be fixed and added as a test please?

**Comment by gnitsua** [comment]
So the issue here is that the old code relied on variables being instantiated before the model is run. In the new code, we don't store these variables in `z` anymore, but just pass them where they are needed. When we rewrote GMSWriter, we wrote it such that it outputs the result of the model (and actually added the ability to do this via a command line argument). So where before when you ran GMSWriter before running the model in the old code there was already a zero for `UnsatStorCarryover`, we wanted to output the value after running the model which depends on variables such as `NYrs` which are created by running `Parser`. 

TL;DR:
There are three potential outputs of GMSWriter:

- GMS file before Parser is run
- GMS file after Parser is run
- GMS file after the model is run

Which of these three do you use? Currently we output the 3rd one, but that assumed that Parser was called before which is why you see an error

**Comment by rajadain** [comment]
Given that [our code](https://github.com/WikiWatershed/model-my-watershed/blob/3d4361f3273c1df507079bec33747a679e7f060d/src/mmw/apps/modeling/tasks.py#L426-L440) is this:

```python
pre_z = Parser.DataModel(mapshed_data)
output = StringIO()
writer = Parser.GmsWriter(output)
writer.write(pre_z)
```

We're running `GmsWriter` after initializing the Parser with `Parser.DataModel()`. We use this to generate a GMS file from the JSON representation before the model is run, and then [run the model](https://github.com/WikiWatershed/model-my-watershed/blob/3d4361f3273c1df507079bec33747a679e7f060d/src/mmw/apps/modeling/tasks.py#L332-L353) on that.

So we need the `GmsWriter` to work before the model has been run.

**Comment by drexeleds** [comment]
That sounds good. This should not be that big of an issue, I will plan changing the name of the current GMSWriter to something along the lines of "OutputGMSWriter" and create a new GMSWriter that does this

**Comment by gnitsua** [comment]
That sounds good. This should not be that big of an issue, I will plan changing the name of the current GMSWriter to something along the lines of "OutputGMSWriter" and create a new GMSWriter that does this

**Comment by gnitsua** [comment]
Actually this use case falls under the 1st case. Because you don't call `GmsWriter.read()`, a significant amount of setup code is not run which is why `z.NYrs` does not exist. In the (not very near) future I think that variable initialization should probably be split from the actual file parsing to eliminate this confusion.

**Comment by gnitsua** [comment]
I have added [this test](https://github.com/drexeleds/gwlf-e/blob/f71488ea7af2ac3065e4a84805740b7daa08fa77/test/gmswritertests/test_gms_writer.py) to cover this situation and have modified the `GMSWriter.write()` function to produce the same output as the GMS file I generated using the original code. Could you please check this over and make sure it indeed fixes the issue? If it does I will merge it into `develop`

**Comment by rajadain** [comment]
Thanks. Tested it out, and can confirm that the process is now working. I did have to make one additional change [here](https://github.com/WikiWatershed/model-my-watershed/blob/5a896518a37fcd2314add65e5af344955c6e7dc2/src/mmw/apps/modeling/tasks.py#L349), since `gwlfe.run(z)` now returns a tuple instead of a dict, but the dict I was looking for was the first item in the tuple so it's fine.

That branch can now be merged on to `drexeleds/develop`. Now that I have it running, I'll be testing the values and timings before and after.

**Comment by gnitsua** [comment]
That's great news. I changes the output of run so that it returned `z` because I needed it to write the output GMS (which I guess is unnecessary now). I do think it's still worthwhile because it could allow the output/GMS writing could be modularized in the future (the conversion to JSON that is done currently is a lossy conversion).
